- name: Show Secrets
  hosts: servers
  become: yes

  vars_files:
    - secrets.yml
  
  tasks:
    - name: Show password
      debug:
        msg: "My password is {{ password }}" 
      no_log: true
      
    - name: Show API Key
      debug:
        msg: "My API Key is {{ api_key}}"   
      no_log: true     
